# -*- coding: utf-8 -*-
"""nti_logisticregression.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1LL6K6UW0OoRNdNJkTD3nEW-EJBx_zci5
"""

import pandas as pd

import numpy as np

import matplotlib.pyplot as plt

dataset = pd.read_csv('a.csv')

x = dataset.iloc[:,[2,3]].values
x

y= dataset.iloc[:,-1].values
y

from sklearn.model_selection import train_test_split

x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=.25)

from sklearn.preprocessing import StandardScaler

sm = StandardScaler()

x_train=sm.fit_transform(x_train)

x_test=sm.transform(x_test)

from sklearn.linear_model import LogisticRegression

rg = LogisticRegression()

rg.fit(x_train,y_train)

y_pred = rg.predict(x_test)

from sklearn.metrics import confusion_matrix

cm = confusion_matrix(y_test,y_pred)

cm

ac=0
for i in range(20):
  x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=.25,random_state=0)
  rg.fit(x_train,y_train)
  y_pred = rg.predict(x_test)
  cm = confusion_matrix(y_test,y_pred)
  ac =((cm[0][0]+cm[1][1])/len(y_test))*100
  print(ac)

acv=ac/20
acv







