# -*- coding: utf-8 -*-
"""randomforest.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Fi7gX6oZGd8RjSwqEYbEp41GoHi6zoEf
"""

import matplotlib.pyplot as plt
import numpy as np
import pandas as pd
from sklearn.impute import SimpleImputer

dataset = pd.read_csv('s.csv')

from sklearn.model_selection import train_test_split

from sklearn.preprocessing import LabelEncoder

lb=LabelEncoder()

dataset['Gender']=lb.fit_transform(dataset['Gender'])

dataset = pd.get_dummies(dataset,columns=['Gender'])

print(dataset)

rows_to_select = [1, 2,4,5]
x = dataset.iloc[:,rows_to_select]
x

y=dataset.iloc[:,-3].values
y

x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=.30)

from sklearn.preprocessing import StandardScaler

sm = StandardScaler()

x_train=sm.fit_transform(x_train)

x_test=sm.transform(x_test)

'''from sklearn.tree import DecisionTreeClassifier

cam= DecisionTreeClassifier(criterion='entropy')

cam.fit(x_train,y_train)

y_pred = cam.predict(x_test)'''
from sklearn.ensemble import RandomForestClassifier
cam= RandomForestClassifier( n_estimators=5,   criterion='entropy',random_state=0)
cam.fit(x_train,y_train)
y_pred = cam.predict(x_test)

from sklearn.metrics import confusion_matrix

tacc=0

cm= confusion_matrix(y_test,y_pred)
cm


ac=0
acv=0
for i in range(20):
  x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=.25)
  cam.fit(x_train,y_train)
  y_pred = cam.predict(x_test)
  cm = confusion_matrix(y_test,y_pred)
  ac =(cm[0][0]+cm[1][1])/(len(y_test))*100
  print(ac)
  acv+=ac/20

acv