# -*- coding: utf-8 -*-
"""speech_to_txt.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Wa2JLImZYXR5LDAs2WPdtzabUlKphryN
"""

pip install SpeechRecognition

pip install gtts

import speech_recognition as sr

r=sr.Recognizer()

filename= '16-122828-0002.wav'

#open the file
with sr.AudioFile(filename) as source:
  # listen for data (load audio to memory)
  audio_data = r.record(source)
  #recognize (convert from speech to text)
  text = r.recognize_google(audio_data,language='en')
  print(text)