# -*- coding: utf-8 -*-
"""text_to_speach.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/17hOpLsfBKJ-4anbYZJpEgBeHeUankCnn
"""

'''google text to speach
              |
              u          '''
pip install gtts

import gtts
from gtts import gTTS

#textx i want to convert
mytest = 'hello world'

#langu in which you want to convert
language = 'en'

#slow = true so the reading speed is fasr
myobj=gTTS(text=mytest,lang=language,slow=False)

#to save the audio in mp3
myobj.save('welcome.mp3')

import IPython
IPython.display.Audio('welcome.mp3')

#textx i want to convert
mytest = 'مرحبا بكم'

#langu in which you want to convert
language = 'ar'

#slow = true so the reading speed is fasr
myobj=gTTS(text=mytest,lang=language,slow=False)

#to save the audio in mp3
myobj.save('welcome_arabic.mp3')

import IPython
IPython.display.Audio('welcome_arabic.mp3')

#textx i want to convert
mytest = 'مرحبا بكم'
#langu in which you want to convert
language = 'ar'

#slow = true so the reading speed is fasr
myobj=gTTS(text=mytest,lang=language,slow=False)

#to save the audio in mp3
myobj.save('welcome_arabic1.mp3')
import IPython
IPython.display.Audio('welcome_arabic1.mp3')

#how to change the performer voice offline

#you can change the desired voices from different online libaries

"""
"HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Speech\Voices\Tokens\TTS_MS_EN-US_ZIRA_11.0"

HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Speech\Voices\Tokens\TTS_MS_EN-US_DAVID_11.0

HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Speech\Voices\Tokens\TTS_MS_EN-US_ZIRA_11.0

HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Speech\Voices\Tokens\TTS_MS_EN-GB_HAZEL_11.0
"""

import pyttsx3

# Initialize the TTS engine
engine = pyttsx3.init()

# List available voices
voices = engine.getProperty('voices')
for voice in voices:
    print(f"Voice: {voice.id}")

# Select a specific voice (change the voice ID as needed)
desired_voice_id = "com.apple.speech.synthesis.voice.kyoko"  # Change this to the desired voice ID
engine.setProperty('voice', desired_voice_id)

# Set the speech rate (optional)
engine.setProperty('rate', 150)  # Adjust the value as needed

# Text to be converted to speech
text = "Hello, how are you?"

# Convert text to speech
engine.say(text)

# Play the speech
engine.runAndWait()